sudo: false
language: node_js
node_js: stable
addons:
  firefox: latest
env:
  global:
    - DISPLAY=:99.0
    - JPM_FIREFOX_BINARY=/usr/local/bin/firefox
before_install:
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
script:
  - jpm test
